export const REQUEST_FETCH_ENTRY = 'REQUEST_FETCH_ENTRY';
export const FETCH_ENTRY_SUCCESS = 'FETCH_ENTRY_SUCCESS';
export const FETCH_ENTRY_FAILURE = 'FETCH_ENTRY_FAILURE';
export const NEW_ENTRY_SUCCESS = 'NEW_ENTRY_SUCCESS';
export const NEW_ENTRY_FAILURE = 'NEW_ENTRY_FAILURE';
export const ENTRY_PLAN = 'ENTRY_PLAN';
